// Created by Satheesh (ryanjon2040). Copyright 2024.

#pragma once

#include "AssetTypeCategories.h"
#include "Modules/ModuleManager.h"

class FBlueprintSubsystemEditorModule : public IModuleInterface
{
	
public:

	static EAssetTypeCategories::Type BlueprintSubsystemAssetCategory;
	
    virtual void StartupModule() override;
    virtual void ShutdownModule() override;

private:
	
    void Internal_PrepareAutoGeneratedDefaultEvents();
};
