// Created by Satheesh (ryanjon2040). Copyright 2024.

#include "BlueprintSubsystemEditorModule.h"
#include "AssetToolsModule.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Subsystems/BlueprintGameInstanceSubsystem.h"
#include "Subsystems/BlueprintWorldSubsystem.h"

#define LOCTEXT_NAMESPACE "FBlueprintSubsystemEditorModule"

#define RegisterDefaultEvent(Class, FuncName) \
(FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, Class::StaticClass(), GET_FUNCTION_NAME_CHECKED(Class, FuncName)))

DEFINE_LOG_CATEGORY_STATIC(LogBlueprintSubsystemEditorModule, All, All);

EAssetTypeCategories::Type FBlueprintSubsystemEditorModule::BlueprintSubsystemAssetCategory = static_cast<EAssetTypeCategories::Type>(0);

void FBlueprintSubsystemEditorModule::StartupModule()
{
    UE_LOG(LogBlueprintSubsystemEditorModule, Log, TEXT("Blueprint Subsystem Editor Module started..."));
    Internal_PrepareAutoGeneratedDefaultEvents();

    IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>("AssetTools").Get();
    BlueprintSubsystemAssetCategory = AssetTools.RegisterAdvancedAssetCategory(FName(TEXT("BlueprintSubsystem")), LOCTEXT("BlueprintSubsystemAssetCategory", "Blueprint Subsystem"));
}

void FBlueprintSubsystemEditorModule::ShutdownModule()
{
    FKismetEditorUtilities::UnregisterAutoBlueprintNodeCreation(this);
    UE_LOG(LogBlueprintSubsystemEditorModule, Log, TEXT("Blueprint Subsystem Editor Module shutdown..."));
}

void FBlueprintSubsystemEditorModule::Internal_PrepareAutoGeneratedDefaultEvents()
{
    RegisterDefaultEvent(UBlueprintGameInstanceSubsystem, K2_OnInit);
    RegisterDefaultEvent(UBlueprintGameInstanceSubsystem, K2_OnTick);
    RegisterDefaultEvent(UBlueprintGameInstanceSubsystem, K2_OnDeInit);

    RegisterDefaultEvent(UBlueprintWorldSubsystem, K2_OnInit);
    RegisterDefaultEvent(UBlueprintWorldSubsystem, K2_OnTick);
    RegisterDefaultEvent(UBlueprintWorldSubsystem, K2_OnDeInit);
}

#undef LOCTEXT_NAMESPACE
#undef RegisterDefaultEvent
    
IMPLEMENT_MODULE(FBlueprintSubsystemEditorModule, BlueprintSubsystemEditor)
