// Auto-generated by SOTS DevTools: ensure_plugin_modules
// Minimal runtime module for SOTS_Stats.

#include "Modules/ModuleManager.h"
#include "Logging/LogMacros.h"

DEFINE_LOG_CATEGORY_STATIC(LogSOTS_StatsModule, Log, All);

class FSOTS_StatsModule : public IModuleInterface
{
public:
    virtual void StartupModule() override
    {
        UE_LOG(LogSOTS_StatsModule, Log, TEXT("SOTS_Stats module starting up"));
        // NOTE: Do not touch worlds / GameInstance / assets here.
    }

    virtual void ShutdownModule() override
    {
        UE_LOG(LogSOTS_StatsModule, Log, TEXT("SOTS_Stats module shutting down"));
    }
};

IMPLEMENT_MODULE(FSOTS_StatsModule, SOTS_Stats);

